### ISSUE TITLE
Fatal error `icingacli x509 jobs run`

### ISSUE THREAD

**Issue by t3easy** [Icinga/icingaweb2-module-x509#106]
## Describe the bug
If I run `icingacli x509 jobs run` I get the error:

```
PHP Fatal error:  Uncaught Error: Call to a member function getField() on null in /usr/share/icingaweb2/modules/x509/vendor/dragonmantank/cron-expression/src/Cron/CronExpression.php:154
Stack trace:
#0 /usr/share/icingaweb2/modules/x509/vendor/dragonmantank/cron-expression/src/Cron/CronExpression.php(137): Cron\CronExpression->setPart()
#1 /usr/share/icingaweb2/modules/x509/vendor/dragonmantank/cron-expression/src/Cron/CronExpression.php(116): Cron\CronExpression->setExpression()
#2 /usr/share/icingaweb2/modules/x509/library/X509/Scheduler.php(27): Cron\CronExpression->__construct()
#3 /usr/share/icingaweb2/modules/x509/application/clicommands/JobsCommand.php(63): Icinga\Module\X509\Scheduler->add()
#4 /usr/share/icingaweb2/library/Icinga/Cli/Loader.php(267): Icinga\Module\X509\Clicommands\JobsCommand->runAction()
#5 /usr/share/icingaweb2/library/Icinga/Application/Cli.php(164): Icinga\Cli\Loader->dispatch()
#6 /usr/share/icingaweb2/library/Icinga/Application/Cli.php(154): Icinga\Application\Cli->dispatchOnce()
#7 /usr/share/i in /usr/share/icingaweb2/modules/x509/vendor/dragonmantank/cron-expression/src/Cron/CronExpression.php on line 154
```

## Your Environment

* Icinga Web 2 version and modules (System - About):
   * Icinga Web 2 2.10.0
   * director 1.9.0
   * monitoring 2.10.0
   * vspheredb 1.2.1
   * x509 1.1.0

* Web browser used: Microsoft Edge 99.0.1150.55
* Icinga 2 version used (`icinga2 --version`): 2.13.2
* PHP version used (`php --version`): 7.4.28
* Server operating system and version: Debian GNU/Linux 11

**Comment by nilmerg** [comment]
Hi,

thanks for the report, and sorry. That's a bug in a library we've included and didn't test accordingly. :roll_eyes:
