### ISSUE TITLE
Changing of filter settings throws exception

### ISSUE THREAD

**Issue by Tuxdiver** [Icinga/icingaweb2-module-x509#15]
## Expected Behavior
Changing of filter settings should work :-)

## Current Behavior
PHP Exception

## Steps to Reproduce (for bugs)
1. filter "cert usage" for hostname "foo" -> apply
2. change filter to "foobar" -> enter 
3. enjoy exception:

```
Trying to get invalid filter index "1-1" from "hostname = foo" ("1")
#0 /usr/share/php/Icinga/Web/Widget/FilterEditor.php(658): Icinga\Data\Filter\Filter->getById(String)
#1 /usr/share/php/Icinga/Web/Widget/FilterEditor.php(327): Icinga\Web\Widget\FilterEditor->applyChanges(Array)
#2 /usr/share/php/Icinga/Web/Controller.php(254): Icinga\Web\Widget\FilterEditor->handleRequest(Object(Icinga\Web\Request))
#3 /usr/share/icingaweb2/modules/x509/application/controllers/UsageController.php(67): Icinga\Web\Controller->setupFilterControl(Object(Icinga\Module\X509\FilterAdapter), Array, Array, Array)
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\X509\Controllers\UsageController->indexAction()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#9 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#10 {main}
```

## Your Environment
* Module version (System - About): 1.0.0 (git master c6831d8934f1b6dc34c51b4d13fd4a0b10cd4181)
* Icinga Web 2 version and modules (System - About): 2.6.1
* Icinga 2 version (`icinga2 --version`): r2.10.2-1
* Operating System and version:  Ubuntu 16.04
* Webserver, PHP versions:  apache 2.4.18-2ubuntu3.9, php 7.0.32-0ubuntu0.16.04.1

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I can confirm this. Will be fixed asap.

Best,
Eric

**Comment by lippserd** [comment]
Hi,

Could you please test the related PR?

Cheers,
Eric

**Comment by Tuxdiver** [comment]
Looks good! 
Thanks for fixing it!
