### ISSUE TITLE
Module should ship its composer dependencies

### ISSUE THREAD

**Issue by swizzly** [Icinga/icingaweb2-module-x509#17]
Hi
I downloaded a recent version of the X509 module, and I tried to follow the installation Manual. I installed the dependencies IPL (v0.1.1) and Reactbundle (v0.3.1). Unfortunately, I can't use composer, since my server does not have direct internet access.
When I enable the module, I receive following messages
```
# icingacli module enable x509
PHP Warning:  Uncaught ErrorException: require_once(/usr/share/icingaweb2/modules/x509/vendor/autoload.php): failed to open stream: No such file or directory in /usr/share/icingaweb2/modules/x509/run.php:4
Stack trace:
#0 /usr/share/icingaweb2/modules/x509/run.php(4): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'require_once(/u...', '/usr/share/icin...', 4, Array)
#1 /usr/share/icingaweb2/modules/x509/run.php(4): require_once()
#2 /usr/share/php/Icinga/Application/Modules/Module.php(1227): include('/usr/share/icin...')
#3 /usr/share/php/Icinga/Application/Modules/Module.php(1214): Icinga\Application\Modules\Module->includeScript('/etc/icingaweb2...')
#4 /usr/share/php/Icinga/Application/Modules/Module.php(424): Icinga\Application\Modules\Module->launchRunScript()
#5 /usr/share/php/Icinga/Application/Modules/Manager.php(231): Icinga\Application\Modules\Module->register()
#6 /usr/share/php/Icinga/Application/Modules/Manager.php(303): Icinga\Application\Modules\Manager->loadModule('x509')
#7 /usr/ in /usr/share/icingaweb2/modules/x509/run.php on line 4

Warning: Uncaught ErrorException: require_once(/usr/share/icingaweb2/modules/x509/vendor/autoload.php): failed to open stream: No such file or directory in /usr/share/icingaweb2/modules/x509/run.php:4
Stack trace:
#0 /usr/share/icingaweb2/modules/x509/run.php(4): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'require_once(/u...', '/usr/share/icin...', 4, Array)
#1 /usr/share/icingaweb2/modules/x509/run.php(4): require_once()
#2 /usr/share/php/Icinga/Application/Modules/Module.php(1227): include('/usr/share/icin...')
#3 /usr/share/php/Icinga/Application/Modules/Module.php(1214): Icinga\Application\Modules\Module->includeScript('/etc/icingaweb2...')
#4 /usr/share/php/Icinga/Application/Modules/Module.php(424): Icinga\Application\Modules\Module->launchRunScript()
#5 /usr/share/php/Icinga/Application/Modules/Manager.php(231): Icinga\Application\Modules\Module->register()
#6 /usr/share/php/Icinga/Application/Modules/Manager.php(303): Icinga\Application\Modules\Manager->loadModule('x509')
#7 /usr/ in /usr/share/icingaweb2/modules/x509/run.php on line 4
PHP Fatal error:  Icinga\Application\Modules\Module::main(): Failed opening required '/usr/share/icingaweb2/modules/x509/vendor/autoload.php' (include_path='/usr/share/icingaweb2/library/vendor:.:/opt/rh/rh-php71/root/usr/share/pear:/opt/rh/rh-php71/root/usr/share/php') in /usr/share/icingaweb2/modules/x509/run.php on line 4

Fatal error: Icinga\Application\Modules\Module::main(): Failed opening required '/usr/share/icingaweb2/modules/x509/vendor/autoload.php' (include_path='/usr/share/icingaweb2/library/vendor:.:/opt/rh/rh-php71/root/usr/share/pear:/opt/rh/rh-php71/root/usr/share/php') in /usr/share/icingaweb2/modules/x509/run.php on line 4
```
I am missing the vendor directory, why?

**Comment by lippserd** [comment]
Hi,

Do you know what composer is? It pulls in missing dependencies. You don't have them because you did not/could not run composer 😆 I'll upload the vendor libs as tarball for you tomorrow.
The first release of this module is not too far away. The composer deps will be shipped then.

Best,
Eric

**Comment by swizzly** [comment]
Hi Eric
Thank you. I understood, that composer installs the missing dependencies, but it does need internet access, doesn't it? And the host where I wanted to install X509 does not have internet. I can hardly wait for the first release, thanks.
Cheers 
Swizzly

**Comment by lippserd** [comment]
Hi,

The related PR should contain the composer deps. Could you please give it a try?

Best,
Eric

**Comment by swizzly** [comment]
Hi Eric

It works!

Many thanks
Swizzly

**Comment by lippserd** [comment]
You're welcome. I'll merge the PR asap for our first release.
