### ISSUE TITLE
Error on scanning a special network

### ISSUE THREAD

**Issue by ChristianMoritz** [Icinga/icingaweb2-module-x509#25]
Im able to scan all subnet's with the scan job, but only one special network doesnt work. and the cli job run's into an error
my job: icingacli x509 scan --job campus

## Context

```
Array to string conversion
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(8, 'Array to string...', '/usr/share/icin...', 315, Array)
#1 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(315): PDOStatement->execute(Array)
#2 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(351): ipl\Sql\Connection->prepexec('INSERT INTO x50...')
#3 /usr/share/icingaweb2/modules/x509/library/X509/CertificateUtils.php(246): ipl\Sql\Connection->insert('x509_certificat...', Array)
#4 /usr/share/icingaweb2/modules/x509/library/X509/Job.php(240): Icinga\Module\X509\CertificateUtils::findOrInsertCert(Object(ipl\Sql\Connection), Resource id #3562, Array)
#5 [internal function]: Icinga\Module\X509\Job->Icinga\Module\X509\{closure}(Object(ipl\Sql\Connection))
#6 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(452): call_user_func(Object(Closure), Object(ipl\Sql\Connection))
#7 /usr/share/icingaweb2/modules/x509/library/X509/Job.php(251): ipl\Sql\Connection->transaction(Object(Closure))
#8 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(25): Icinga\Module\X509\Job->Icinga\Module\X509\{closure}(Object(React\Socket\Connection))
#9 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure))
#10 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#11 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#12 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(React\Socket\Connection))
#13 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure))
#14 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#15 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#16 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise-timer/src/functions.php(31): React\Promise\Promise::React\Promise\{closure}(Object(React\Socket\Connection))
#17 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(25): React\Promise\Timer\{closure}(Object(React\Socket\Connection))
#18 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure))
#19 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#20 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#21 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(25): React\Promise\Promise::React\Promise\{closure}(Object(React\Socket\Connection))
#22 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure))
#23 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#24 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#25 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(React\Socket\Connection))
#26 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(66): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure))
#27 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#28 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#29 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(React\Socket\Connection))
#30 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure))
#31 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#32 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#33 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(React\Socket\Connection))
#34 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure))
#35 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#36 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#37 [internal function]: React\Promise\Promise::React\Promise\{closure}(NULL)
#38 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Deferred.php(36): call_user_func(Object(Closure), NULL)
#39 /usr/share/icingaweb2/modules/reactbundle/vendor/react/socket/src/StreamEncryption.php(137): React\Promise\Deferred->resolve()
#40 /usr/share/icingaweb2/modules/reactbundle/vendor/react/socket/src/StreamEncryption.php(95): React\Socket\StreamEncryption->toggleCrypto(Resource id #3351, Object(React\Promise\Deferred), true, 57)
#41 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(238): React\Socket\StreamEncryption->React\Socket\{closure}(Resource id #3351)
#42 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(205): React\EventLoop\StreamSelectLoop->waitForStreamActivity(2226982)
#43 /usr/share/icingaweb2/modules/x509/library/X509/Job.php(311): React\EventLoop\StreamSelectLoop->run()
#44 /usr/share/icingaweb2/modules/x509/application/clicommands/ScanCommand.php(51): Icinga\Module\X509\Job->run()
#45 /usr/share/php/Icinga/Cli/Loader.php(265): Icinga\Module\X509\Clicommands\ScanCommand->indexAction()
#46 /usr/share/php/Icinga/Application/Cli.php(149): Icinga\Cli\Loader->dispatch()
#47 /usr/share/php/Icinga/Application/Cli.php(139): Icinga\Application\Cli->dispatchOnce()
#48 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#49 {main}
```

## Steps to Reproduce (for bugs)
21 other subnets could be scanned without error.
the network to scan is an internal network in my campus.
"10.11.252.0/24"

## Your Environment
* Module version (System - About): 1.0.0
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): 2.10.1-2
* Operating System and version: Ubuntu 16.04
* Webserver, PHP versions: 7

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Could you please test PR #13? It may be a certificate with multiple CNs which leads to this error.

Best,
Eric

**Comment by nilmerg** [comment]
Hi Christian,

the mentioned PR is now part of the master. Any chance for your feedback whether your issue is solved?
