### ISSUE TITLE
Use SSL when connecting to MySQL

### ISSUE THREAD

**Issue by MrStrix** [Icinga/icingaweb2-module-x509#30]
We want to connect to MySQL over SSL.

## Expected Behavior
Our options in `resources.ini` are ([documentation](https://icinga.com/docs/icingaweb2/latest/doc/04-Resources/#database)):
```ini
[x509_db]
type = "db"
db = "mysql"
host = "db.local"
port = "3306"
dbname = "x509"
username = "x509"
password = "passw0rd"
charset = "utf8"
use_ssl = "1"
ssl_ca = "/etc/pki/tls/certs/ca-bundle.crt"
```
I expect PDO to ose SSL with the specified CA certificate.

## Current Behavior
The optional options are not recognized. I get the following error message:
```
SQLSTATE[HY000] [9002] SSL connection is required. Please specify SSL options and retry.

#0 /etc/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(146): PDO->__construct(String, String, String, Array)
#1 /etc/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(161): ipl\Sql\Connection->createPdoAdapter()
#2 /etc/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(312): ipl\Sql\Connection->connect()
#3 /etc/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(331): ipl\Sql\Connection->prepexec(String, Array)
#4 /etc/icingaweb2/modules/x509/application/controllers/UsageController.php(126): ipl\Sql\Connection->select(Object(ipl\Sql\Select))
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\X509\Controllers\UsageController->indexAction()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#11 {main}
```
This is our MySQL trying to enforce SSL. When I dump the options that are used to connect, the specified options are missing:
```
/etc/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php:142:
array (size=7)
  19 => int 2
  1002 => string 'SET SESSION SQL_MODE='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'' (length=121)
  8 => int 0
  20 => boolean false
  3 => int 2
  11 => int 0
  17 => boolean false
```
This is the output of `var_dump($adapter->getOptions($config))` used in https://github.com/Icinga/ipl-sql/blob/3932b3e8082c32246d66ae3653666c2381b43484/src/Connection.php#L146 to create the new connection.

## Possible Solution

Configuration options specified in icinga2 documentation should be passed to $config

## Steps to Reproduce (for bugs)

1. add Database for x509 module as shown above
2. go to https://your-server/x509/certificates

## Your Environment

* Module version (System - About): x509: 1.0.0
* Icinga Web 2 version and modules (System - About): 
```
    audit | 1.0.0
    graphite | 1.1.0
    ipl | v0.1.1
    monitoring | 2.6.2
    reactbundle | v0.4.1
    x509 | 1.0.0
```
* Icinga 2 version (`icinga2 --version`): 
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.2-1)

Copyright (c) 2012-2018 Icinga Development Team (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-862.11.6.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```
* Operating System and version: CentOS Linux release 7.5.1804 (Core) with Linux 3.10.0-862.11.6.el7.x86_64
* Webserver, PHP versions: 
```
# nginx -v
nginx version: nginx/1.14.2
# php -v
PHP 7.1.8 (cli) (built: Aug  9 2017 13:20:06) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
```

**Comment by Al2Klimov** [comment]
@lippserd We should transfer this issue to https://github.com/Icinga/ipl-sql, shouldn't we?

**Comment by MrStrix** [comment]
> @lippserd We should transfer this issue to https://github.com/Icinga/ipl-sql, shouldn't we?

I don't think so. The problem lies in https://github.com/Icinga/icingaweb2-module-x509/blob/d6e795e1ec668e91b689ea86177d2fbed71fb801/library/X509/Controller.php#L34
Where `$config` is not correctly populated. ipl-sql uses these options to connect correctly.

**Comment by nilmerg** [comment]
This needs to be supported by `ipl-sql` first.

@MrStrix It's not the module's task to translate the resource configuration into applicable PDO driver options. It even isn't its own configuration format after all.

I'll re-open the referenced issue above instead.
