### ISSUE TITLE
Support for peer_certificate_chain without client certificate on servers that require client certificates

### ISSUE THREAD

**Issue by flybyray** [Icinga/icingaweb2-module-x509#66]
## Is your feature request related to a problem? Please describe.
The scan job should be able to scan targets which require client certificates.
Sometimes such targets disconnect the connection when there is no client certificate presented.
At the moment the x509 module cannot handle server terminated connections and behaves as if this is an error.

## Describe the solution you'd like
The peer certificates chain is even available if the connection is server terminated.
The message "failed during TLS handshake" indicates that the handshake took place and server certificates were most likely presented.

It is easy to prove that reactphp/socket's `SecureConnector.php` has retrieved the needed chain.
```diff
--- src/SecureConnector.php	(revision a831b9451df0b751fe2a0d035e6cb8c578544394)
+++ src/SecureConnector.php	(date 1579090742701)
@@ -58,8 +58,15 @@
             // try to enable encryption
             return $promise = $encryption->enable($connection)->then(null, function ($error) use ($connection, $uri) {
                 // establishing encryption failed => close invalid connection and return error
+                $stream = $connection->stream;
+                $options = stream_context_get_options($stream);
+
                 $connection->close();

+                $chain = $options['ssl']['peer_certificate_chain'];
+                \var_dump($chain);
+
+
                 throw new \RuntimeException(
                     'Connection to ' . $uri . ' failed during TLS handshake: ' . $error->getMessage(),
                     $error->getCode()
```
This patch will output something like:
```text
Connecting to tls://[127.0.0.1]:4043 [SNI hostname: client.badssl.com]
array(2) {
  [0]=>
  resource(997) of type (OpenSSL X.509)
  [1]=>
  resource(998) of type (OpenSSL X.509)
}
Cannot connect to server: Connection to [127.0.0.1]:4043 failed during TLS handshake: Unable to complete TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure, trace: #0 /etc/icingaweb2/modules/reactbundle/vendor/react/promise/src/RejectedPromise.php(25): React\Socket\SecureConnector->React\Socket\{closure}(Object(UnexpectedValueException))
```
the relevant stacktrace shows that this information is available even in the error case `Job.php(349)`.
```
#1 /etc/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(134): React\Promise\RejectedPromise->then(NULL, Object(Closure))
...
#11 /etc/icingaweb2/modules/reactbundle/vendor/react/socket/src/StreamEncryption.php(139): React\Promise\Deferred->reject(Object(UnexpectedValueException))
#12 /etc/icingaweb2/modules/reactbundle/vendor/react/socket/src/StreamEncryption.php(81): React\Socket\StreamEncryption->toggleCrypto(Resource id #995, NULL, true, 57)
#13 /etc/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(244): React\Socket\StreamEncryption->React\Socket\{closure}(Resource id #995)
#14 /etc/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(211): React\EventLoop\StreamSelectLoop->waitForStreamActivity(4981338)
#15 /etc/icingaweb2/modules/x509/library/X509/Job.php(349): React\EventLoop\StreamSelectLoop->run()
#16 /etc/icingaweb2/modules/x509/application/clicommands/ScanCommand.php(50): Icinga\Module\X509\Job->run()
#17 /usr/share/php/Icinga/Cli/Loader.php(265): Icinga\Module\X509\Clicommands\ScanCommand->indexAction()
#18 /usr/share/php/Icinga/Application/Cli.php(152): Icinga\Cli\Loader->dispatch()
#19 /usr/share/php/Icinga/Application/Cli.php(142): Icinga\Application\Cli->dispatchOnce()
#20 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#21 {main}

```

## Describe alternatives you've considered

* If the server configuration can be adjusted, you can of course not terminate the connection and present an error page.

Otherwise there are no alternatives that i am aware of.

## Additional context
No conext

**Comment by lippserd** [comment]
Hi,

Since react does not support intercepting the connection close handling in any way, I came up with a highly hackish approach. Please feel free to test the related PR. Though, I'm not quite sure whether we really merge this. I'll get in touch with the react devs to see what we can do here.

Cheers,
Eric

**Comment by lippserd** [comment]
I found a less hacky approach which actually mergeable. I'd love your feedback on this @flybyray
