### ISSUE TITLE
Missing function: gmp_import

### ISSUE THREAD

**Issue by iDemonix** [Icinga/icingaweb2-module-x509#7]
I've got php-gpm installed, but the module doesn't seem to want to use it:

```
[root@icinga2-master1 ~]$icingacli x509 scan --job Test --debug
PHP Fatal error:  Uncaught Error: Call to undefined function Icinga\Module\X509\gmp_import() in /usr/share/icingaweb2/modules/x509/library/X509/Job.php:65
Stack trace:
#0 /usr/share/icingaweb2/modules/x509/library/X509/Job.php(97): Icinga\Module\X509\Job::addrToNumber('194.238.49.0')
#1 [internal function]: Icinga\Module\X509\Job::generateTargets(Object(Icinga\Data\ConfigObject), Object(Icinga\Application\Config))
#2 /usr/share/icingaweb2/modules/x509/library/X509/Job.php(286): iterator_count(Object(Generator))
#3 /usr/share/icingaweb2/modules/x509/application/clicommands/ScanCommand.php(51): Icinga\Module\X509\Job->run()
#4 /usr/share/php/Icinga/Cli/Loader.php(265): Icinga\Module\X509\Clicommands\ScanCommand->indexAction()
#5 /usr/share/php/Icinga/Application/Cli.php(149): Icinga\Cli\Loader->dispatch()
#6 /usr/share/php/Icinga/Application/Cli.php(139): Icinga\Application\Cli->dispatchOnce()
#7 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#8 {main}
  thrown in /usr/share/icingaweb2/modules/x509/library/X509/Job.php on line 65
```

But the function is available:

```
[root@icinga2-master1 ~]$php -a
Interactive shell

php > echo gmp_import('192.168.2.0');
59507465716345299339980336
```

**Comment by lippserd** [comment]
Did you restart PHP FPM afterward? Which OS are you using? Which PHP packages are installed? Especially the gmp one.

**Comment by iDemonix** [comment]
I restarted PHP-FPM and the entire server for good measure.

OS is CentOS 7.4, PHP is 7 and the package for gmp is `php70u-gmp-7.0.32-1.ius.centos7.x86_64`

```
[root@icinga2-master1 ~]$php -v
PHP 7.0.32 (cli) (built: Sep 13 2018 16:50:42) ( NTS )
```

**Comment by lippserd** [comment]
If you've installed Icinga Web 2 via our packages, you have to install the gmp module from Red Hat's Software Collections. Either `rh-php71-php-gmp` or `rh-php70-php-gmp`. Depending on the PHP version you've installed. You may check this with `rpm -qa | grep php`.

**Comment by iDemonix** [comment]
Thanks, that solved my issue!

**Comment by lippserd** [comment]
You're welcome. Please star this module, if you like it.
