### ISSUE TITLE
Services import source fails with MySQL 8+

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingaweb2-module-x509#97]
The following error appears when previewing results in the director:

```
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'x509.c.subject' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (Connection.php:401)
#0 /usr/local/src/ipl-sql/src/Connection.php(401): PDO->prepare('SELECT t.ip AS ...')
#1 /usr/local/src/ipl-sql/src/Connection.php(418): ipl\Sql\Connection->prepexec('SELECT t.ip AS ...', Array)
#2 /usr/share/icingaweb2-modules/x509/library/X509/ProvidedHook/ServicesImportSource.php(71): ipl\Sql\Connection->select(Object(ipl\Sql\Select))
#3 /usr/share/icingaweb2-modules/director/library/Director/Web/Table/ImportsourceHookTable.php(100): Icinga\Module\X509\ProvidedHook\ServicesImportSource->fetchData()
#4 /usr/share/icingaweb2-modules/incubator/vendor/gipfl/icingaweb2/src/Table/SimpleQueryBasedTable.php(29): Icinga\Module\Director\Web\Table\ImportsourceHookTable->prepareQuery()
#5 /usr/share/icingaweb2-modules/incubator/vendor/gipfl/icingaweb2/src/Table/SimpleQueryBasedTable.php(15): gipfl\IcingaWeb2\Table\SimpleQueryBasedTable->getQuery()
#6 /usr/share/icingaweb2-modules/incubator/vendor/gipfl/icingaweb2/src/Table/QueryBasedTable.php(56): gipfl\IcingaWeb2\Table\SimpleQueryBasedTable->getPaginationAdapter()
#7 /usr/share/icingaweb2-modules/incubator/vendor/gipfl/icingaweb2/src/Table/QueryBasedTable.php(255): gipfl\IcingaWeb2\Table\QueryBasedTable->getPaginator(Object(gipfl\IcingaWeb2\Url))
#8 /usr/share/icingaweb2-modules/director/application/controllers/ImportsourceController.php(162): gipfl\IcingaWeb2\Table\QueryBasedTable->renderTo(Object(Icinga\Module\Director\Controllers\ImportsourceController))
#9 /icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ImportsourceController->previewAction()
#10 /icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('previewAction')
#11 /icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /icingaweb2/library/Icinga/Application/Web.php(301): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#13 /icingaweb2/library/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#14 /icingaweb2/public/index.php(4): require_once('/icingaweb2/lib...')
#15 {main}
```

I'm using MySQL 8 and I highly suspect that's the reason. Didn't test on a lower MySQL version, though.

**Comment by Al2Klimov** [comment]
Yep. It's MySQL 8. Didn’t get IW2 connect to it, but var_dump()ed the query and...

```
mysql> SELECT t.ip AS host_ip, t.hostname AS host_name, t.port AS host_port, c.subject AS cert_subject, c.issuer AS cert_issuer, COALESCE(ci.self_signed, c.self_signed) AS cert_self_signed, c.trusted AS cert_trusted, c.valid_from AS cert_valid_from, c.valid_to AS cert_valid_to, HEX(c.fingerprint) AS cert_fingerprint, GROUP_CONCAT(CONCAT(dn.key, '=', dn.value) SEPARATOR ',') AS cert_dn, (SELECT GROUP_CONCAT(CONCAT(can.type, ':', can.value) SEPARATOR ',') FROM x509_certificate_subject_alt_name can WHERE can.certificate_id = c.id GROUP BY can.certificate_id) AS cert_subject_alt_name FROM x509_target t INNER JOIN x509_certificate_chain cc ON cc.id = t.latest_certificate_chain_id INNER JOIN x509_certificate_chain_link ccl ON ccl.certificate_chain_id = cc.id INNER JOIN x509_certificate c ON c.id = ccl.certificate_id LEFT JOIN x509_certificate ci ON ci.subject_hash = c.issuer_hash LEFT JOIN x509_dn dn ON dn.hash = c.subject_hash WHERE ccl.order = 0 GROUP BY t.ip, t.hostname, t.port;
ERROR 1055 (42000): Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'x5.c.subject' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
mysql>
```

5.5.68-MariaDB purrs. 🐈‍⬛
